# Generated by Django 5.0.3 on 2024-03-27 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_course_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='revieqs_qty',
            new_name='reviews_qty',
        ),
    ]
